### ISSUE TITLE
problem discovery

### ISSUE THREAD

**Issue by Filipe-Mariano** [t1bur1an/ros_bgp#1]
![screen shot 08-30-16 at 09 23 am](https://cloud.githubusercontent.com/assets/11853709/18088891/7e3a04ea-6e93-11e6-8ebf-0eaa08f8de41.PNG)

**Comment by t1bur1an** [comment]
Hi!
Can you run this script manual and put output in comment in this thread?

**Comment by Filipe-Mariano** [comment]
![screen shot 09-01-16 at 08 24 am](https://cloud.githubusercontent.com/assets/11853709/18165778/9abd32a0-701d-11e6-9f85-a7da9aecc3ed.PNG)

**Comment by t1bur1an** [comment]
You have wrong copy of files. I think you copy html pages, not scripts sources. Just download archive and unpack for get normal files.
https://github.com/t1bur1an/ros_bgp/archive/master.zip

**Comment by Filipe-Mariano** [comment]
hmm....can be i will try ...otherwise can u check that Key? bgpdiscovery_ros.py this file do not exist in your zip , and it was set in ur external monitoring discovery

**Comment by Filipe-Mariano** [comment]
where this file? /usr/share/zabbix/externalscripts/**bgpdiscovery_ros.py**: [2] No such file or directory

**Comment by t1bur1an** [comment]
script name fixed in template. look in new commit
